### ISSUE TITLE
Project Progress Report

### ISSUE THREAD

**Issue by howardre** [howardre/ORnearshore_groundfish#3]
[Project_Report.pdf](https://github.com/howardre/ORnearshore_groundfish/files/5483353/Project_Report.pdf)

**Comment by zechmeunier** [comment]
Seems like you've made a ton of progress!

**Comment by Angelika-Kurthen** [comment]
I really enjoyed your description of what you did to clean up old data. I'm dealing with a code I wrote when I was learning R as well, and it isn't easy.

**Comment by Juniper41** [comment]
Great job! Looks like your data is starting to shape up and become clearer!

**Comment by jwongala** [comment]
It was great getting to see all of the progress you made, especially with modularizing your code.

**Comment by Coffee-Powered-Scientist** [comment]
Good progress, are you a tidyverse or base R kind of R user?

**Comment by McLeodMJ** [comment]
Great progress Rebecca! I am curious to hear how you went about working with confidential data in Github, I will have to do so myself in the coming months.

**Comment by jessealaney** [comment]
Seems like you've really made progress on your coding in terms of reformatting, condensing, and debugging. Great job modularizing scripts into functions and dealing w/ private data.
