### ISSUE TITLE
Project Summary

### ISSUE THREAD

**Issue by howardre** [howardre/ORnearshore_groundfish#4]

**Comment by howardre** [comment]
[summary_presentation.pdf](https://github.com/howardre/ORnearshore_groundfish/files/5624506/summary_presentation.pdf)

**Comment by McLeodMJ** [comment]
Hi Rebecca,
Great progress on your repository! I may be reaching out to you about how to manage such a large dataset and techniques you used towards faster computing. Awesome work and I am excited to see your manuscript!
